### Data Preprocessing

### Feature Selection

In [3]:
from sklearn.preprocessing import Imputer
import pandas as pd


In [4]:
df=pd.read_csv('data.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [5]:
impute=Imputer(missing_values='NaN',strategy='mean',axis=0)
df.iloc[:,1:3]=impute.fit_transform(df.iloc[:,1:3])

C:\Users\Niharika Menon\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [6]:
df.head()

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes

### Encoding Categorical Data

In [7]:
from sklearn.preprocessing import LabelEncoder

In [9]:
temp=df.copy()
labelenc=LabelEncoder()

In [11]:
temp.iloc[:,0]=labelenc.fit_transform(temp.iloc[:,0])
temp.head()

Country   Age        Salary Purchased
0        0  44.0  72000.000000        No
1        2  27.0  48000.000000       Yes
2        1  30.0  54000.000000        No
3        2  38.0  61000.000000        No
4        1  40.0  63777.777778       Yes

### Feature Scaling

 In ML models, features are mapped into nD space. If we consider two variables (x,y), they'll be plotted in 2D space. Assuming, one value is small and the other value is big, the Eucledian Distance will be dominated by the bigger value and the smaller one will be ignored. This causes loss of data/information 

 Other reasons for feature scaling:
   1. to make relationships between variables more linear
   2. to make data distribution more symmetric
   3. to make data more consistent in variance (homoscedastically)
   

##### Most used methods of feature scaling:
    Min Max
    Normalizing
    Standardizing
    Log Transformation
    

In [15]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, Normalizer

In [16]:
df=pd.read_csv('data.csv').dropna()

In [17]:
x=df[['Age','Salary']].values.astype(np.float64)

In [18]:
s=StandardScaler()
m=MinMaxScaler()
n=Normalizer()

print("Standardization")
print(s.fit_transform(x))
print("Min Max")
print(m.fit_transform(x))
print("NOrmalization")
print(n.fit_transform(x))

Standardization
[[ 0.69985807  0.58989097]
 [-1.51364653 -1.50749915]
 [-1.12302807 -0.98315162]
 [-0.08137885 -0.37141284]
 [-0.47199731 -0.6335866 ]
 [ 1.22068269  1.20162976]
 [ 1.48109499  1.55119478]
 [-0.211585    0.1529347 ]]
Min Max
[[0.73913043 0.68571429]
 [0.         0.        ]
 [0.13043478 0.17142857]
 [0.47826087 0.37142857]
 [0.34782609 0.28571429]
 [0.91304348 0.88571429]
 [1.         1.        ]
 [0.43478261 0.54285714]]
NOrmalization
[[6.11110997e-04 9.99999813e-01]
 [5.62499911e-04 9.99999842e-01]
 [5.55555470e-04 9.99999846e-01]
 [6.22950699e-04 9.99999806e-01]
 [6.03448166e-04 9.99999818e-01]
 [6.07594825e-04 9.99999815e-01]
 [6.02409529e-04 9.99999819e-01]
 [5.52238722e-04 9.99999848e-01]]
